### ISSUE TITLE
Batch conversion jobs stack with each cron run

### ISSUE THREAD

**Issue by heyheyhello** [cwilby/nextcloud-workflow-media-converter#159] opened 2021-12-30 10:03 UTC
## Steps to reproduce

1. Set a batch conversion that takes longer than the default Nextcloud cron period of 5 minutes. For me this is 10 files.
2. Wait for the first `php cron.php` to run, calling this app to begin converting
3. Wait for the second `cron.php` to run, calling this app **again**

### Expected behaviour

The conversion script notices its already running in another cron job and exits, leaving only one cron job ever running.

### Actual behaviour

The conversion script job runs alongside the existing job using the same queue. For the default cron period of 5 minutes, this easily causes the system to run out of resources since FFMPEG takes a lot of CPU and RAM each run (thank you for adding the `--threads=` option).

![image](https://user-images.githubusercontent.com/44614862/147741540-7c479e70-da1a-4a25-9286-5546f511aedf.png)

**Operating system**: Debian 11

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 8.0

**Nextcloud Version:** 22.2.0

**Where did you install Nextcloud from:** Tar.gz?

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

I understand that this could be seen as not an issue with the converter, since it's a general cron issue of "what to do when the next job is reached but the previous job isn't done"and that logic is very application specific. However - the default Nextcloud cron time for installations as mentioned in their docs is 5 minutes https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html?highlight=cron#cron, which is very very low for media conversion.

Thanks for the great software it has helped a ton with avoid proprietary iOS MOV auto uploads!

**Comment by cwilby** [comment] 2021-12-31 22:02
Not ideal :)

Working on a solution where each conversion job must obtain and release a "lock" during runtime.
A job may obtain a lock when it is the next job in the conversion batch and there is not an active "lock".
When another job is dispatched, and the lock is active, or the job is not the next conversion in the batch, it should push itself to the back of the queue.

Another option I considered was creating a "ConvertBatch" job that converts each video sequentially.  The issue is that job would be subject to retry in the NC job engine after 15 minutes, recreating the problem.

Will keep you posted 👍

**Comment by heyheyhello** [comment] 2021-12-31 22:07
Awesome thanks for the update! Yeah on a RaspberryPi sometimes 15 minutes isn't even enough time to convert one video 😅

**Comment by cwilby** [comment] 2022-01-01 00:47
Work in progress: https://github.com/cwilby/nextcloud-workflow-media-converter/commit/14c1a29b09122e21751bfbd28febd46fe58cec5d

**Comment by cwilby** [comment] 2022-01-02 06:17
Added a `Convert media in parallel` switch when creating a batch:
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13686317/147867770-ad6fcb83-1d8a-4dc1-b38c-4bf683307ca4.png">

Added the same to admin settings:
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13686317/147867774-0b0607cb-77a5-482c-8cd3-910c107190eb.png">

When parallel conversion is checked in admin settings, media will be converted in parallel.  If it is unchecked, jobs will be re-queued if another conversion is currently running.

**Comment by cwilby** [comment] 2022-01-03 08:15
Version 1.3.3 has been released with the ability to disable parallel conversion.  

You can now go to `Admin Settings > Media conversion` to change this setting.

![image](https://user-images.githubusercontent.com/13686317/147910018-f1ffb053-032f-4281-8540-9dd57f973a8c.png)

When the setting is checked, batch conversions and workflow-triggered conversions should run sequentially (one-at-a-time).

When unchecked, conversions actually still run sequentially. This is just how queued jobs work in Owncloud/Nextcloud.  

That said - the stacking effect should be resolved by checking whether a per-batch lock (or global lock for workflow conversions) is active.  If it is, the conversion is re-queued so the current conversion can finish.  If it is not, the conversion will acquire a lock and continue.  If deadlock is encountered, the lock will be released after 30 minutes.. ad finitum.

... should reduce the load on your RaspberryPI!  Happy new year 🥂

**Closed by cwilby** 2022-01-03 08:15 UTC

**Comment by heyheyhello** [comment] 2022-01-03 08:34
I've downloaded the new version and will try it out - thanks for the speedy release! This should help a lot with the load and temperature. Happy new year ✨
