### ISSUE TITLE
Can't create Media conversion as user

### ISSUE THREAD

**Issue by dmgeurts** [cwilby/nextcloud-workflow-media-converter#84] opened 2021-10-02 14:48 UTC
## Steps to reproduce
1. Manually add app to NC (21)
2. Enable app in NC
3. User user's profile, try to add the conversion

![image](https://user-images.githubusercontent.com/2071992/135720926-df799e32-9d89-43bf-a0ff-3821d909aac5.png)

When creating the conversion workflow as admin, no error is thrown. Instead, it's showing a pulsating Queued button and the progress bar remains grey. The folder the operation is being attempted on is a shared group folder. Does that matter? If it does then an alert to the user would be helpful, to suggest they make a request to the admin for creating the rule.

![image](https://user-images.githubusercontent.com/2071992/135720834-87d57caf-c2e3-4b1d-b13f-d5b2eed150d9.png)

**** Update: for admin user the process completed after some time.

### Expected behaviour
Expect to see flow saved

### Actual behaviour
Error "Error saving
{message}"

## Automated Media Conversion

v1.2.10

## Server configuration
Issue Template is listed as incompatible with NC-21

**Operating system**: Ubuntu 20.04

**Web server:** Apache2

**Database:** 10.3.31-MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 21.0.5.1

**Where did you install Nextcloud from:** Updated online from version 18 or 19, which was manually installed

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

<details>
```
Enabled:                  
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - analytics: 3.6.1
  - announcementcenter: 5.0.1
  - bruteforcesettings: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.5
  - epubreader: 1.4.6
  - external: 3.8.2
  - facerecognition: 0.8.3
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_antivirus: 3.2.2
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.2
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - flow_notifications: 1.1.0
  - geoblocker: 0.5.1
  - groupfolders: 9.0.3
  - guests: 2.0.2
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.10.5
  - mediadc: 0.1.2
  - metadata: 0.14.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.11.0
  - recognize: 1.6.10
  - recommendations: 1.0.0
  - registration: 1.3.0
  - richdocuments: 4.2.3
  - richdocumentscode: 6.4.1103
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - sociallogin: 4.8.7
  - socialsharing_email: 2.2.0
  - spreed: 11.3.2
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - talk_matterbridge: 1.22.4
  - tasks: 0.14.2
  - terms_of_service: 1.7.1
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_nextcloud_notification: 3.2.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - video_converter: 1.0.3
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflow_media_converter: 1.2.10
  - workflow_script: 1.6.0
  - workflowengine: 2.3.1
Disabled:
  - calendar
  - contacts
  - encryption
  - federation
  - files_external
  - support
  - user_ldap
```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "team.bethanycc.uk"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.5.1",
        "overwrite.cli.url": "https:\/\/team.bethanycc.uk",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "default_phone_region": "GB",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "social_login_auto_redirect": false,
        "default_language": "en_GB",
        "default_locale": "en_GB",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "forcessl": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Server log (data/nextcloud.log)
<details>
```
No log entries reported when trying to create an automated workflow
```
</details>

**Comment by cwilby** [comment] 2021-11-14 05:45
Closing this as it appears that the batch went through after some time.

Note: There can be a lead time on background jobs in Nextcloud, depending on the job engine being used.  https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html

**Closed by cwilby** 2021-11-14 05:45 UTC

**Comment by olaulau** [comment] 2024-09-25 22:29
this issue still happens as of today :
- non admin users cannot create batch conversion
- the error message doesn't appears correctly in the popup

**Comment by ruedigerkupper** [comment] 2024-11-12 13:38
Please reopen this issue, as it is still valid. 

Your comment
> Closing this as it appears that the batch went through after some time.
seems to be a misunderstanding of @dmgeurts updated comment: He only stated that batch jobs for **the admin** do actually run, **but not for regular users**.
As of NC 29.0.4, regular users cannot use batch processing with symptoms exactly as described above.

Thank you for reopening!

**Comment by ruedigerkupper** [comment] 2024-11-12 14:16
Ah, duplicate of #459 (open).
