### ISSUE TITLE
Can't select codec only output format, additionally most output formats are missing. And even for the available ones no settings whatsoever are available!

### ISSUE THREAD

**Issue by Pingger** [cwilby/nextcloud-workflow-media-converter#134] opened 2021-11-12 20:28 UTC

**Comment by cwilby** [comment] 2021-11-12 21:19
IIRC I have built out codec configuration per output format that is not currently visible in the UI.

This required significant time commitment on my part, and given I already built out the features I wanted and shared with the community for free,  this will most likely happen once I get the ball rolling and contributors fill in the blanks.  

This issue is a good starting point if you are looking to contribute: https://github.com/cwilby/nextcloud-workflow-media-converter/issues/30

Otherwise, closing as a duplicate of #30.

**Closed by cwilby** 2021-11-12 21:19 UTC
